<a href="https://colab.research.google.com/github/geeta7777chavan-boop/python-practicals/blob/main/practical_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Name : Geeta Santosh Chavan**

**Roll No. : AIDS-SY-A-66**

# **Practical No. 2**

# **Aim:**  
Data Ingestion and Cleaning: Acquire data and prepare it for analysis.

# **Theory :**

**1. What is data ingestion and why is it important in data science? Which Python library is commonly used for data ingestion and cleaning?**

Data Ingestion is the process of acquiring, collecting, and importing raw data from various external sources (such as CSV files, databases, APIs, web scraping, cloud storage, etc.) into a system or tool where it can be stored and processed for further analysis.

**Importance in Data Science:**

1. It is the first and foundational step of any data science pipeline.
Without proper ingestion, data remains inaccessible for analysis or modeling.
2. It ensures data is brought into a structured format (e.g., DataFrame) so that cleaning, exploration, and modeling can begin.
3. Poor ingestion can lead to incomplete, corrupted, or inconsistent data, which ultimately affects the accuracy and reliability of insights and machine learning models.

Commonly used Python Library:
Pandas is the most popular and widely used library for both data ingestion and data cleaning. It provides powerful functions like read_csv(), read_excel(), read_sql(), etc., along with extensive tools for data manipulation and cleaning.

**2. Why is data cleaning necessary before performing analysis or machine learning?**

Raw data collected from real-world sources is almost never perfect. It usually contains missing values, duplicates, inconsistent formats, outliers, incorrect data types, and noise.

**Reasons why data cleaning is essential:**

1. Garbage In → Garbage Out (GIGO): Machine learning models and statistical analysis are highly sensitive to poor-quality data. Even small errors can lead to misleading conclusions or poor model performance.
2. Improves accuracy and reliability of results.
3. Helps in better feature engineering and model training.
4. Prevents errors during computation (e.g., division by zero or type mismatch).
5. Saves computational resources and time by removing unnecessary or faulty records.
6. Ensures data consistency and data integrity, which is critical for making correct business or scientific decisions.

In short, data cleaning transforms raw, messy data into high-quality, analysis-ready data.

**3. How do you load a CSV file into a Pandas DataFrame?**

A CSV (Comma-Separated Values) file is one of the most common formats for storing tabular data.
To load a CSV file into a Pandas DataFrame, we use the following syntax:
Pythonimport pandas as pd

Loading a CSV file

df = pd.read_csv('filename.csv')

If the file is in a different folder, provide the full path:
df = pd.read_csv('/content/drive/MyDrive/data/myfile.csv')

Optional useful parameters:

header=None → if the CSV has no header row

1. index_col=0 → to set a specific column as index

2. usecols=['col1','col2'] → to load only selected columns

3. dtype={'col1': 'int64'} → to specify data types

After loading, we can verify using df.head() or df.info().

**4. What is the difference between head() and tail() functions in Pandas?**

These are two very useful methods to quickly inspect the dataset without printing the entire DataFrame.
| Feature    | head()            | tail()         |
| ---------- | ----------------- | -------------- |
| Rows shown | First rows        | Last rows      |
| Default    | 5 rows            | 5 rows         |
| Purpose    | Beginning preview | Ending preview |

**5. How can you identify missing values in a dataset?**

Missing values (represented as NaN, None, or blank) can severely affect analysis and machine learning models. Pandas provides simple and effective methods to detect them.

Common methods to identify missing values:

In [ ]:
# 1. Check total missing values per column
df.isnull().sum()

# 2. Check percentage of missing values
(df.isnull().sum() / len(df)) * 100

# 3. Get overall summary of missing values
df.isna().sum()

# 4. Visual check (boolean DataFrame)
df.isnull().head()

# 5. Get complete information about the dataset
df.info()



*   isnull() and isna() are the same (both return True where value is missing).
*   After identification, missing values can be handled using dropna() or fillna().

# **Program:**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving ecommerce_orders_10k_updated.csv to ecommerce_orders_10k_updated.csv

In [ ]:
import pandas as pd

df = pd.read_csv("ecommerce_orders_10k_updated.csv")

## **1. Display First 5 Rows** **and Last 5 Rows**

In [ ]:
df.head()

,order_id,user_id,product_id,category,price,qty,total_price,order_date,country,customer_segment
0,100000,861,201,Sports,93.11,2,186.22,2024-10-30 16:07:37,Brazil,Mid-Value
1,100001,1295,366,Home,101.09,1,101.09,2022-04-17 09:31:40,Canada,Low-Value
2,100002,1131,115,Electronics,253.61,1,253.61,2022-11-08 12:38:20,India,Mid-Value
3,100003,1096,159,Clothing,11.73,2,23.46,2022-05-18 17:24:55,India,Low-Value
4,100004,1639,42,Electronics,743.98,2,1487.96,2024-01-25 05:51:54,Canada,High-Value

In [ ]:
df.tail()

,order_id,user_id,product_id,category,price,qty,total_price,order_date,country,customer_segment
9995,109995,2226,68,Toys,64.81,1,64.81,2023-05-08 06:41:03,Canada,Low-Value
9996,109996,2890,246,Toys,75.49,1,75.49,2024-06-25 01:10:51,Spain,Low-Value
9997,109997,1378,389,Clothing,6.51,2,13.02,2023-02-14 12:10:05,India,Low-Value
9998,109998,1178,138,Sports,37.08,1,37.08,2025-07-26 12:28:58,France,Low-Value
9999,109999,1950,308,Toys,17.90,1,17.90,2023-01-07 01:34:33,Spain,Low-Value

# **2. Identify Missing Values**

In [ ]:
df.isnull().sum()

order_id            0
user_id             0
product_id          0
category            0
price               0
qty                 0
total_price         0
order_date          0
country             0
customer_segment    0
dtype: int64

# **3. Rename Columns to Lowercase**

In [ ]:
df.columns = df.columns.str.lower()
df.columns

Index(['order_id', 'user_id', 'product_id', 'category', 'price', 'qty',
       'total_price', 'order_date', 'country', 'customer_segment'],
      dtype='object')

# **4. Display Dataset Shape**

In [ ]:
print("Rows and Columns:", df.shape)

Rows and Columns: (10000, 10)

# **5. Remove Duplicate Rows**

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          10000 non-null  int64
 1   user_id           10000 non-null  int64
 2   product_id        10000 non-null  int64
 3   category          10000 non-null  object
 4   price             10000 non-null  float64
 5   qty               10000 non-null  int64
 6   total_price       10000 non-null  float64
 7   order_date        10000 non-null  object
 8   country           10000 non-null  object
 9   customer_segment  10000 non-null  object
dtypes: float64(2), int64(4), object(4)
memory usage: 781.4+ KB

In [ ]:
df.describe()

,order_id,user_id,product_id,price,qty,total_price
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,104999.50000,1502.626900,249.510700,103.141911,1.550400,159.583117
std,2886.89568,865.021722,144.079787,123.602789,1.012404,249.380101
min,100000.00000,1.000000,1.000000,1.370000,1.000000,1.380000
25%,102499.75000,762.750000,124.000000,25.350000,1.000000,31.477500
50%,104999.50000,1493.000000,252.000000,55.375000,1.000000,74.200000
75%,107499.25000,2250.250000,373.000000,128.285000,2.000000,182.682500
max,109999.00000,3000.000000,500.000000,901.730000,5.000000,3487.850000

# **Conclusion :**
In this practical on Data Ingestion and Cleaning, we understood that data ingestion is the critical first step that brings raw data into the Python environment using the powerful Pandas library. We also learned that data cleaning is not just optional but a mandatory preprocessing stage because real-world data is usually incomplete, inconsistent, and noisy.
By mastering techniques such as loading CSV files, inspecting data with head() and tail(), and identifying missing values, we prepare a clean, reliable dataset that forms a strong foundation for accurate exploratory data analysis and successful machine learning model building.